version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/code
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.6"
            apt-get update -q
            apt-get install -yq curl python-pip git
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Run basic tests
          working_directory: ~/code
          command: |
            pip install -r test_requirements.txt
            bash verify.sh
      - run:
          name: Run integration tests
          working_directory: ~/code/integration-test
          command: ./run.sh
